2018-09-10 10:18:18,833 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 10:40:19,843 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 10:40:28,856 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 11:01:32,015 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 11:13:25,491 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 11:14:45,313 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 11:15:15,521 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 11:17:09,763 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 11:20:26,939 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 11:20:30,320 ERROR: Exception on /messages [GET] [in /home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/yoj/devman/microblog/app/main/routes.py", line 248, in messages
    next_url=next_url, prev_url=prev_url)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/yoj/devman/microblog/app/templates/messages.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/yoj/devman/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 26, in block "body"
    {% block scripts %}
  File "/home/yoj/devman/microblog/app/templates/base.html", line 125, in block "scripts"
    $.ajax('{{ url_for('main.notifications') }}?since=' + since).done(
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.notifications'. Did you mean 'main.unfollow' instead?
2018-09-10 11:27:16,837 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 11:27:24,785 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 11:36:19,015 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
2018-09-10 11:36:31,798 ERROR: Exception on /send_message/kotka [GET] [in /home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yoj/devman/microblog/.venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/yoj/devman/microblog/app/main/routes.py", line 224, in send_message
    if form.validate_on_submit():
TypeError: validate_on_submit() missing 1 required positional argument: 'self'
2018-09-10 11:40:49,672 INFO: Microblog startup [in /home/yoj/devman/microblog/app/__init__.py:85]
